[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['neosnippet-snippets']
on_i = 1
on_ft = ['snippet']

# Lang

[[plugins]] # Haml
repo  = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Golang
repo = 'fatih/vim-go'
on_ft = 'go'

[[plugins]] # TMUX
repo = 'tmux-plugins/vim-tmux'
on_ft = 'tmux'

[[plugins]] # toml
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd']
hook_add = '''
  let g:vim_markdown_frontmatter = 1
  let g:vim_markdown_math = 1
'''
[[plugins]]
repo = 'jiangmiao/auto-pairs'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = { 
  \   'colorscheme': 'wombat'
  \ }
'''

# Colors

[[plugins]] # hybrid
repo = 'w0ng/vim-hybrid'

[[plugins]] # solarized
repo = 'altercation/vim-colors-solarized'

[[plugins]] # zenburn
repo = 'jnurmine/Zenburn'


[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'
